CREATE DATABASE HelpSmart;

USE HelpSmart;

CREATE TABLE CUSTOMERS(
    CODIGO INT AUTO_INCREMENT NOT NULL ,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(10),
    CPF VARCHAR(11),
    PRIMARY KEY (CODIGO)
);

ALTER TABLE CUSTOMERS MODIFY TELEFONE VARCHAR(14);
ALTER TABLE CUSTOMERS ADD COLUMN ATIVO BOOLEAN;